export const ADDRESS_REQUEST = 'ADDRESS_REQUEST';
export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS';
export const ADDRESS_FAIL = 'ADDRESS_FAIL';

export const MIN_ADDRES_COUNTRY_LENGTH = 0;
export const MIN_ADDRES_CITY_LENGTH = 1;
export const MIN_ADDRES_POSTAL_CODE_LENGTH = 2;
export const MIN_ADDRES_STREET_LENGTH = 2;
export const MIN_ADDRES_HOME_NUMBER_LENGTH = 1;