export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

export const PRODUCT_SEARCHBAR_REQUEST = 'PRODUCT_SEARCHBAR_REQUEST';
export const PRODUCT_SEARCHBAR_SUCCESS = 'PRODUCT_SEARCHBAR_SUCCESS';
export const PRODUCT_SEARCHBAR_FAIL = 'PRODUCT_SEARCHBAR_FAIL';


export const PRODUCT_DESCRIPTION_LENGTH = 750;